/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.algebra;

import hr.algebra.dal.Repository;
import hr.algebra.dal.RepositoryFactory;
import hr.algebra.model.user.User;
import hr.algebra.utils.FormUtils;
import hr.algebra.utils.MessageUtils;

import java.awt.Dimension;

import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;

import javax.swing.text.JTextComponent;

/**
 *
 * @author Jo
 */
public class LogInMainForm extends javax.swing.JFrame {

    private List<JTextComponent> fieldsReg;
    private List<JLabel> labelsReg;
    private List<JTextComponent> fieldsLog;
    private List<JLabel> labelsLog;
    private Repository repository;
    //   private JTabbedPane tpContent = new JTabbedPane(JTabbedPane.TOP);

    /**
     * Creates new form LogInMainForm
     */
    public LogInMainForm() {
        try {
            initComponents();
            init();

        } catch (IOException ex) {
            Logger.getLogger(LogInMainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblErrLName = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblErrUsernameReg = new javax.swing.JLabel();
        tfUsernameLogIn = new javax.swing.JTextField();
        lblErrPasswordReg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblErrConPasswordReg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfUsernameRegistration = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfLastNameRegistration = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfFirstNameRegistration = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pfPasswordLogin = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        pfPasswordReg = new javax.swing.JPasswordField();
        lblErrUsernameLogIn = new javax.swing.JLabel();
        pfConPasswordReg = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnOKRegistration = new javax.swing.JButton();
        btnCancelRegistration = new javax.swing.JButton();
        btnCancelLogIn = new javax.swing.JButton();
        btnOKLogIn = new javax.swing.JButton();
        lblErrPasswordLogIn = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblErrFName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(230, 230, 249));
        setPreferredSize(new java.awt.Dimension(1192, 768));

        Panel.setBackground(new java.awt.Color(230, 230, 249));
        Panel.setPreferredSize(new java.awt.Dimension(1192, 768));
        Panel.setRequestFocusEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("LOG IN ");

        lblErrLName.setForeground(new java.awt.Color(255, 51, 102));

        jLabel10.setText("Username:");

        lblErrUsernameReg.setForeground(new java.awt.Color(255, 51, 102));

        tfUsernameLogIn.setNextFocusableComponent(pfPasswordLogin);

        lblErrPasswordReg.setForeground(new java.awt.Color(255, 51, 102));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr/assets/default-avatar.png"))); // NOI18N

        lblErrConPasswordReg.setForeground(new java.awt.Color(255, 51, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRATION:");

        jLabel3.setText("Username:");

        tfUsernameRegistration.setNextFocusableComponent(pfPasswordReg);

        jLabel4.setText("Password:");

        tfLastNameRegistration.setNextFocusableComponent(tfUsernameRegistration);

        jLabel5.setText("First name:");

        tfFirstNameRegistration.setNextFocusableComponent(tfLastNameRegistration);

        jLabel11.setText("Password:");

        pfPasswordLogin.setToolTipText("");
        pfPasswordLogin.setNextFocusableComponent(btnOKLogIn);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        pfPasswordReg.setNextFocusableComponent(pfConPasswordReg);

        lblErrUsernameLogIn.setForeground(new java.awt.Color(255, 51, 51));

        pfConPasswordReg.setNextFocusableComponent(btnOKRegistration);

        jLabel6.setText("Last name:");

        jLabel7.setText("Confirm password:");

        btnOKRegistration.setText("OK");
        btnOKRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKRegistrationActionPerformed(evt);
            }
        });

        btnCancelRegistration.setBackground(new java.awt.Color(255, 153, 153));
        btnCancelRegistration.setText("Cancel");
        btnCancelRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelRegistrationActionPerformed(evt);
            }
        });

        btnCancelLogIn.setBackground(new java.awt.Color(255, 153, 153));
        btnCancelLogIn.setText("Cancel");
        btnCancelLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelLogInActionPerformed(evt);
            }
        });

        btnOKLogIn.setText("OK");
        btnOKLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKLogInActionPerformed(evt);
            }
        });

        lblErrPasswordLogIn.setForeground(new java.awt.Color(255, 51, 102));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr/assets/default-avatar.png"))); // NOI18N

        lblErrFName.setForeground(new java.awt.Color(255, 51, 102));

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfUsernameLogIn)
                                    .addComponent(pfPasswordLogin)))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(btnOKLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrPasswordLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrUsernameLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addGap(98, 98, 98)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(tfLastNameRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblErrLName, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfUsernameRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfFirstNameRegistration, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblErrFName, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblErrUsernameReg, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(btnOKRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(btnCancelRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pfConPasswordReg, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pfPasswordReg, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblErrPasswordReg, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblErrConPasswordReg, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(852, 912, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(PanelLayout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(tfUsernameLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pfPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblErrPasswordLogIn)))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(lblErrUsernameLogIn)))
                                .addGap(53, 53, 53)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnOKLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCancelLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfFirstNameRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblErrFName)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblErrLName)
                                    .addComponent(tfLastNameRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfUsernameRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblErrUsernameReg)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pfPasswordReg, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblErrPasswordReg))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pfConPasswordReg, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblErrConPasswordReg))
                                .addGap(32, 32, 32)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnOKRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCancelRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1915, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 306, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKRegistrationActionPerformed
        Regiser();

    }//GEN-LAST:event_btnOKRegistrationActionPerformed

    private void btnCancelRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelRegistrationActionPerformed
        fieldsReg.forEach((field) -> {
            field.setText("");
        });
        labelsReg.forEach((field) -> {
            field.setText("");
        });
    }//GEN-LAST:event_btnCancelRegistrationActionPerformed

    private void btnCancelLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelLogInActionPerformed
        clearLogInForm();

        labelsLog.forEach((field) -> {
            field.setText("");
        });
    }//GEN-LAST:event_btnCancelLogInActionPerformed

    private void btnOKLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKLogInActionPerformed
        if (FormUtils.formValid(fieldsLog, labelsLog)) {
            try {
                int ID = getUserId();

                Optional<User> user = RepositoryFactory.getUserRepository().selectOne(ID);
                if (!user.isPresent()) {
                    MessageUtils.showErrorMessage("No user", "Wrong username or password");
                    clearLogInForm();

                } else if (user.get().getUserRoleID() == 1) {

                    JFrame f = new Admin();
                    f.setVisible(true);
                    f.setPreferredSize(new Dimension(1192, 768));
                    setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    dispose();

                } else {
                    JFrame f1 = new User_gui();
                    f1.setVisible(true);
                    f1.setPreferredSize(new Dimension(1192, 768));
                    setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    dispose();
                }

            } catch (Exception ex) {
                Logger.getLogger(LogInMainForm.class.getName()).log(Level.SEVERE, null, ex);
                MessageUtils.showErrorMessage("Error", "Unable to fetch user");
            }
        }

    }//GEN-LAST:event_btnOKLogInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnCancelLogIn;
    private javax.swing.JButton btnCancelRegistration;
    private javax.swing.JButton btnOKLogIn;
    private javax.swing.JButton btnOKRegistration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblErrConPasswordReg;
    private javax.swing.JLabel lblErrFName;
    private javax.swing.JLabel lblErrLName;
    private javax.swing.JLabel lblErrPasswordLogIn;
    private javax.swing.JLabel lblErrPasswordReg;
    private javax.swing.JLabel lblErrUsernameLogIn;
    private javax.swing.JLabel lblErrUsernameReg;
    private javax.swing.JPasswordField pfConPasswordReg;
    private javax.swing.JPasswordField pfPasswordLogin;
    private javax.swing.JPasswordField pfPasswordReg;
    private javax.swing.JTextField tfFirstNameRegistration;
    private javax.swing.JTextField tfLastNameRegistration;
    private javax.swing.JTextField tfUsernameLogIn;
    private javax.swing.JTextField tfUsernameRegistration;
    // End of variables declaration//GEN-END:variables
 private int getUserId() throws Exception {
        List<User> users = RepositoryFactory.getUserRepository().selectList();
        for (User user : users) {
            String temp = new String(pfPasswordLogin.getPassword());

            if (user.getUsername().equals(tfUsernameLogIn.getText().trim()) && user.getPassword().equals(temp)) {
                return user.getID();

            }
        }
        return 0;

    }

    private void initValidation() {
        fieldsReg = Arrays.asList(tfFirstNameRegistration, tfLastNameRegistration, tfUsernameRegistration, pfPasswordReg, pfConPasswordReg);
        labelsReg = Arrays.asList(lblErrFName, lblErrLName, lblErrUsernameReg, lblErrPasswordReg, lblErrConPasswordReg);
        fieldsLog = Arrays.asList(tfUsernameLogIn, pfPasswordLogin);
        labelsLog = Arrays.asList(lblErrUsernameLogIn, lblErrPasswordLogIn);
    }

    private void init() throws IOException {
        initValidation();
        initRepository();
    }

    private void initRepository() throws IOException {
        repository = RepositoryFactory.getUserRepository();
    }

    private void checkPass() {
        if (!Arrays.equals(pfPasswordReg.getPassword(), pfConPasswordReg.getPassword())) {
            MessageUtils.showErrorMessage("Error", "Password and confirm password MUST match");
        }
    }

    private void Regiser() {
        checkPass();

        if (FormUtils.formValid(fieldsReg, labelsReg)) {
            try {
                User user = new User(
                        tfFirstNameRegistration.getText().trim(),
                        tfLastNameRegistration.getText().trim(),
                        tfUsernameRegistration.getText().trim(),
                        new String(pfPasswordReg.getPassword())
                );

                repository.createOne(user);
                fieldsReg.forEach((field) -> {
                    field.setText("");
                });
                MessageUtils.showInformationMessage("Registration", "Registration succsessful, please LOG IN to continue!");

            } catch (Exception ex) {
                MessageUtils.showErrorMessage("Error", "Unable to register user");
            }
        }

    }

    private void clearLogInForm() {
        tfUsernameLogIn.setText("");
        pfPasswordLogin.setText("");
    }

}
